### ISSUE TITLE
NameError: name 'target_idx' is not defined

### ISSUE THREAD

**Issue by glenn-jocher** [yiyixuxu/polyloss-pytorch#2]
README example is not reproducible as `target_idx` does not exist.

```python
import torch
from PolyLoss import to_one_hot, PolyLoss
# Example of target in one-hot encoded format
loss = PolyLoss(softmax=True)
B, C, H, W = 2, 5, 3, 3
input = torch.rand(B, C, H, W, requires_grad=True)
target = torch.randint(low=0, high=C - 1, size=(B, H, W)).long()
target = to_one_hot(target_idx[:, None, ...], num_classes=C)
output = loss(input, target)
output.backward()

...

Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/yolov5-pro/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-0534d4642825>", line 8, in <module>
    target = to_one_hot(target_idx[:, None, ...], num_classes=C)
NameError: name 'target_idx' is not defined
```

**Comment by yiyixuxu** [comment]
I fixed it. Thank you!
